services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
