name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-win-build:
    name: Check build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - run: cargo build --features generate-bindings,bundled
